language: cpp
compiler:
- g++
os:
- linux
install:
- sudo pip install codecov
script:
- make
- make test
- make gcov
branches:
    only:
    - master
after_success:
- codecov -t 32d40052-1af9-4c67-86f9-71ae61d748d4 -X gcov
